### ISSUE TITLE
Code: Burger Dispenser

### ISSUE THREAD

**Issue by EntranceJew** [GoonHouse/SAGDCX#8]
In the demo scene, the floating burgers are denoting where they should be on  a rotating shelf.
Create (out of primatives if necessary) a multi-level tray that can hold five of each ingredient on each side. The individual layers should be able to rotate freely to switch what kind of burger or cheese you have selected before dragging it to the burger.

**Comment by ghost** [comment]
Taking the credit for my burg dispenser
